# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Bigu"
description: > # this means to ignore newlines until "email:"
   Carona universitária com &#9829;

email: gabriel_almeida@me.com
#blog logo
logo: "/assets/images/bigu_logo.jpg"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Bigu'
author: 'Bigu'
author_image: "/assets/images/bigu_logo.jpg"

paginate:	5

url: "http://blog.bigu.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@bigu'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/bigu
    desc: Segue a gente no Twitter!
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/bigu
#    desc: Curta nossa página no Facebook!
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/biguHQ
    desc: Colabore conosco no Github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
